# Generated by Django 4.2.18 on 2025-02-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
