# Generated by Django 4.2.18 on 2025-01-25 11:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(max_length=200)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('building', models.CharField(max_length=200)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('number_of_tables', models.PositiveSmallIntegerField()),
                ('number_of_chairs', models.PositiveSmallIntegerField()),
                ('kitchen', models.BooleanField()),
                ('tea_and_coffeemaker', models.BooleanField()),
                ('projector', models.BooleanField()),
                ('audio_equipment', models.BooleanField()),
                ('childrens_play_area', models.BooleanField()),
                ('piano', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
