# Generated by Django 4.2.18 on 2025-01-25 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSpaceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Denied')], default=0)),
                ('event_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_space_bookings_by_space', to='dashboard.eventspace')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_space_bookings_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
